INSERT INTO DELEGACIAS (ID, NOME, ID_PROF) VALUES (1, 'CENTRO-SUL', 362);
INSERT INTO DELEGACIAS (ID, NOME, ID_PROF) VALUES (2, 'NOROESTE', 10337);
INSERT INTO DELEGACIAS (ID, NOME, ID_PROF) VALUES (3, 'NORTE', 703);
INSERT INTO DELEGACIAS (ID, NOME, ID_PROF) VALUES (4, 'OESTE', 11545);
INSERT INTO DELEGACIAS (ID, NOME, ID_PROF) VALUES (5, 'SUL', 1434);
INSERT INTO DELEGACIAS (ID, NOME, ID_PROF) VALUES (0, 'NENHUM', NULL);


