
CREATE TABLE ACADEMIAS (
    CODIGO           INTEGER NOT NULL,
    RAZAO            VARCHAR(60) ,
    CNPJ             VARCHAR(14),
    CPF              VARCHAR(11),
    RG               VARCHAR(15),
    INSCRICAO        VARCHAR(17) ,
    FANTASIA         VARCHAR(30) ,
    CONTATO          VARCHAR(40) ,
    ENDERECO         VARCHAR(40) ,
    BAIRRO           VARCHAR(20) ,
    NUMERO           VARCHAR(10),
    COMPLEMENTO      VARCHAR(30) ,
    CIDADE           VARCHAR(40) ,
    ESTADO           VARCHAR(2) ,
    CEP              VARCHAR(8),
    FONE             VARCHAR(50),
    TIPOFILIACAO     CHAR(1),
    PRITECNICO       VARCHAR(50) ,
    SEGTECNICO       VARCHAR(50) ,
    MENSALIDADE      INTEGER,
    ETIQ             CHAR(1),
    CORRESPONDENCIA  VARCHAR(50),
    CODPROF          INTEGER,
    ID_DELEGACIA     SMALLINT,
    COD_TECNICO      INTEGER,
    PTO_TECNICO      INTEGER DEFAULT 0,
    EMAIL            VARCHAR(40),
    DTCADASTRO       DATE
);

CREATE TABLE APROVADOS (
    CODCAND        INTEGER NOT NULL,
    DATAPROMO      DATE NOT NULL,
    ID_FAIXA_DE    INTEGER,
    ID_FAIXA_PARA  INTEGER,
    NOTA           DECIMAL(4,1),
    LOCAL          VARCHAR(30)
);

CREATE TABLE CALENDARIO (
    ID          INTEGER NOT NULL,
    CODEVENTO   INTEGER,
    DATAEVENTO  DATE,
    VERSAO      VARCHAR(20),
    LOCAL       VARCHAR(30),
    TIPO        SMALLINT DEFAULT 0,
    NIVEL       SMALLINT DEFAULT 1,
    SIT         INTEGER DEFAULT 1
);

CREATE TABLE CATEGORIAS (
    ID         INTEGER NOT NULL,
    DESCRICAO  VARCHAR(30),
    IDADE_MIN  INTEGER,
    IDADE_MAX  INTEGER,
    SEXO       CHAR(1)
);

CREATE TABLE ATLETAS (
    CODIGO            INTEGER NOT NULL,
    NOME              VARCHAR(50) ,
    CPF               VARCHAR(11),
    RG                VARCHAR(15),
    SEXO              VARCHAR(9) DEFAULT 'MASCULINO',
    DATANASC          DATE,
    NACIONALIDADE     VARCHAR(20) DEFAULT 'BRASILEIRA',
    NATURALIDADE      VARCHAR(20) ,
    UFNATURALIDADE    CHAR(2),
    ENDERECO          VARCHAR(40) ,
    BAIRRO            VARCHAR(20) ,
    NUMERO            VARCHAR(10),
    COMPLEMENTO       VARCHAR(30) ,
    CIDADE            VARCHAR(40) ,
    ESTADO            VARCHAR(2) DEFAULT 'PR',
    CEP               VARCHAR(8),
    FONE              VARCHAR(20),
    CONJUGE           VARCHAR(40) ,
    NASCCONJ          DATE,
    NOMEMAE           VARCHAR(40) ,
    NOMEPAI           VARCHAR(40) ,
    TIPOREGISTRO      CHAR(1),
    CERTIDAONASC      VARCHAR(15) ,
    EMAIL             VARCHAR(40) ,
    ACADEMIA          INTEGER DEFAULT 0,
    CODCBJ            VARCHAR(12),
    ANUIDADE          VARCHAR(4),
    SUSPENDERPROMO    CHAR(1) DEFAULT 'S',
    OBSERVACAO        VARCHAR(1000) ,
    DATAULTPROMO      DATE,
    DATAPROMO_ANT     DATE,
    ESTADOCIVIL       VARCHAR(15) DEFAULT 'SOLTEIRO(A)',
    FAIXAATUAL        VARCHAR(25) ,
    ID_FAIXA          INTEGER DEFAULT 1,
    IMPRIMIRSELO      CHAR(1) DEFAULT 'S',
    DTCADASTRO        DATE,
    CELULAR           VARCHAR(15),
    VIASELO           CHAR(1) DEFAULT '1',
    CODPROF           INTEGER,
    PTOARBITRAGEM     INTEGER DEFAULT 0,
    PTOCURSOS         INTEGER DEFAULT 0,
    PTOCOMPETICAO     INTEGER DEFAULT 0,
    PONTOS            INTEGER DEFAULT 0,
    PTOPROF           INTEGER DEFAULT 0,
    FOTO              VARCHAR(250),
    SIT_EXAME         SMALLINT DEFAULT 0,
    CREF              VARCHAR(15),
    IMPRIMIRCARTEIRA  CHAR(1) DEFAULT 'N',
    NOME_CART         VARCHAR(27) 
);

CREATE TABLE DELEGACIAS (
    ID       SMALLINT NOT NULL,
    NOME     VARCHAR(20),
    ID_PROF  INTEGER
);

CREATE TABLE DIVISOES (
    ID    INTEGER NOT NULL,
    NOME  VARCHAR(20)
);

CREATE TABLE FAIXAS (
    ID         INTEGER NOT NULL,
    SEQ        SMALLINT DEFAULT 0 NOT NULL,
    NOME       VARCHAR(20),
    NIVEL      SMALLINT DEFAULT 0,
    IDADE_MIN  SMALLINT DEFAULT 0,
    KYU        INTEGER DEFAULT 0,
    DAN        INTEGER DEFAULT 0
);

CREATE TABLE HISTORICO_ALUNOS (
    ID      INTEGER NOT NULL,
    DATA    DATE,
    CODIGO  INTEGER,
    MEMO    VARCHAR(128),
    FLAG    SMALLINT DEFAULT 0
);

CREATE TABLE MENSALIDADES (
    CODACAD       INTEGER NOT NULL,
    ANO           SMALLINT NOT NULL,
    MES           SMALLINT NOT NULL,
    DATAEMISSAO   DATE,
    RECNRO        VARCHAR(20),
    VALORMENSAL   DECIMAL(8,2),
    TIPOFILIACAO  CHAR(1)
);

CREATE TABLE PARTICIPACOES (
    CODCAND        INTEGER NOT NULL,
    CODEVENTO      INTEGER NOT NULL,
    CODATIV        SMALLINT NOT NULL,
    PTO            INTEGER,
    TIPOATIV       CHAR(1),
    PTO_COMPUTADO  CHAR(1) DEFAULT 'N',
    PERCENTUAL     INTEGER DEFAULT 100,
    ID_FAIXA       INTEGER,
    FAIXA          VARCHAR(15),
    ANO            INTEGER,
    OBS            VARCHAR(128)
);

CREATE TABLE PERFIS (
    ID    INTEGER NOT NULL,
    NOME  VARCHAR(20)
);

CREATE TABLE PERMISSOES (
    ID_PERFIL  INTEGER NOT NULL,
    NAME       VARCHAR(30) NOT NULL,
    NOME       VARCHAR(60),
    PERMISSAO  CHAR(1)
);

CREATE TABLE PESOS (
    ID_CAT    INTEGER NOT NULL,
    ID_DIV    INTEGER NOT NULL,
    PESO_MIN  DECIMAL(8,3),
    PESO_MAX  DECIMAL(8,3),
    SEXO      CHAR(1) DEFAULT 'M'
);

CREATE TABLE RANK_RESULTADOS (
    ID         INTEGER NOT NULL,
    ANO        INTEGER NOT NULL,
    CODIGO     INTEGER NOT NULL,
    PONTOS     INTEGER,
    CODTEC     INTEGER,
    PTO_TEC    INTEGER,
    COLOCACAO  SMALLINT,
    CATEGORIA  VARCHAR(20),
    DIVISAO    VARCHAR(15),
    MEMO       VARCHAR(128)
);

CREATE TABLE RANKING (
    ANO        INTEGER NOT NULL,
    CODATLETA  INTEGER NOT NULL,
    PONTOS     INTEGER DEFAULT 0,
    DATA       DATE DEFAULT CURRENT_DATE,
    POSICAO    INTEGER DEFAULT 0
);

CREATE TABLE RANKING_TEC (
    ANO          INTEGER NOT NULL,
    COD_TECNICO  INTEGER NOT NULL,
    PONTOS       INTEGER DEFAULT 0,
    DATA         DATE DEFAULT CURRENT_DATE,
    POSICAO      INTEGER DEFAULT 0
);

CREATE TABLE TABATIV (
    CODATIV            SMALLINT NOT NULL,
    DESCRICAO          VARCHAR(40),
    TIPO               CHAR(1),
    VINCULADO          CHAR(1) DEFAULT 'S',
    PTO_REGIONAL       INTEGER,
    PTO_ESTADUAL       INTEGER,
    PTO_SUL            INTEGER,
    PTO_NACIONAL       INTEGER,
    PTO_INTERNACIONAL  INTEGER,
    PTO                DECIMAL(4,1)
);

CREATE TABLE TABEVENTOS (
    CODEVENTO   INTEGER NOT NULL,
    DATAEVENTO  DATE,
    LOCAL       VARCHAR(30),
    NIVEL       CHAR(1),
    DESCRICAO   VARCHAR(100),
    TIPO        CHAR(1) DEFAULT '1' NOT NULL,
    SIT         CHAR(1)
);

CREATE TABLE TABMINIMA (
    GRAU        INTEGER,
    NOME        VARCHAR(30),
    MESESPERM   INTEGER,
    PONTOS      INTEGER,
    PERCMINIMO  INTEGER,
    CONTROLARP  CHAR(1),
    IDADE       SMALLINT
);

CREATE TABLE TRANSFERENCIAS (
    CODIGO      INTEGER,
    ACADEMIA    INTEGER,
    DTCADASTRO  DATE
);

CREATE TABLE USUARIOS (
    ID         INTEGER NOT NULL,
    NOME       VARCHAR(30),
    SENHA      VARCHAR(10),
    NIVEL      CHAR(1),
    ATIVO      CHAR(1) DEFAULT 'S',
    ID_PERFIL  INTEGER DEFAULT 2
);



